### ISSUE TITLE
spec_helper.rb:3  undefined method `configure' for RSpec:Module

### ISSUE THREAD

**Issue by stabenfeldt** [burke/zeus#308]
I´m running Rails 3.2.13 and Ruby 2.0.0-p0

**rspec spec/models works**, but it fails with zeus:

``` bash
$ zeus rspec spec/models
zeus rspec spec/models
/Users/martins/Work/Make/Newsmail/spec/spec_helper.rb:3:in `<top (required)>': undefined method `configure' for RSpec:Module (NoMethodError)
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/zeus-0.13.3/lib/zeus/rails.rb:176:in `test_helper'
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/zeus-0.13.3/lib/zeus.rb:166:in `run_action'
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/zeus-0.13.3/lib/zeus.rb:54:in `block in go'
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/zeus-0.13.3/lib/zeus/load_tracking.rb:7:in `features_loaded_by'
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/zeus-0.13.3/lib/zeus.rb:53:in `go'
    from /Users/martins/.rvm/gems/ruby-2.0.0-p0@myapp/gems/zeus-0.13.3/lib/zeus.rb:78:in `block (3 levels) in go'

```

**My spec_helper looks like this:**

``` ruby
ENV['RAILS_ENV'] = 'test'

RSpec.configure do |config|

  require File.expand_path("../../config/environment", __FILE__)
  require 'rspec/rails'
  require 'fabrication'
  require 'faker'
  require 'database_cleaner'
  require 'capybara/poltergeist'

  config.include Capybara::DSL

  config.use_transactional_fixtures = false
  config.infer_base_class_for_anonymous_controllers = false

  Capybara.javascript_driver = :selenium
  #Capybara.javascript_driver = :poltergeist

  options = { :js_errors =>  true }
  Capybara.register_driver :poltergeist do |app|
    Capybara::Poltergeist::Driver.new(app, options)
  end

  ####################
  ## Database Cleaner
  #
  config.before :each do
    if Capybara.current_driver == :rack_test
      DatabaseCleaner.strategy = :transaction
    else
      DatabaseCleaner.strategy = :truncation
    end
    DatabaseCleaner.start
  end


  # Requires supporting ruby files with custom matchers and macros, etc,
  # in spec/support/ and its subdirectories.
  Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f}

  config.after do
    DatabaseCleaner.clean
  end

  config.include(MailerMacros)
    config.before(:each) { reset_email }
  end


```

**Gemfile**

``` ruby

group :test, :development do
  gem 'rspec-rails'
  gem 'parallel_tests'
  gem 'zeus-parallel_tests'
end

group :test do
  gem "rb-fsevent"
  gem "zeus"
  gem 'launchy'
  gem "capybara", :github => "jnicklas/capybara"
  gem "xpath", :github => "jnicklas/xpath"
  gem 'database_cleaner'
  gem 'poltergeist', :git => 'https://github.com/jonleighton/poltergeist.git'
  gem 'selenium-webdriver'
end
```

**Comment by CDainMiller** [comment]
@sushil10018 Killer. Just saved me an hour

**Comment by sushil10018** [comment]
Thanks @CDainMiller ! :)

**Comment by hqt** [comment]
@sushil10018  thanks. it works. Just a little note here, for someone else like me trusting in your solution :"P
