### ISSUE TITLE
"You have already activated json 1.8.0..." with 0.13.4.pre2

### ISSUE THREAD

**Issue by rickmzp** [burke/zeus#378]
Same problem as #368 and #355 with 0.13.4.pre2. I am not using a custom plan. I use rbenv and rbenv-bundler.

Here's the [stacktrace](https://gist.github.com/rickmzp/5a667f4b755ddd025ff1). thanks!

**Comment by daniellboy** [comment]
Works for me too @TylerRick

**Comment by prashant-kajale** [comment]
Thanks @TylerRick  this work around works for me aswell

**Comment by bbuchalter** [comment]
I was able to run `bundle clean --force` to remove all gems not in use in the context of the current gemfile. This of course is just a temporary fix until some other application (using the same version of Ruby as the repo which is having trouble running Zeus) installs some other incompatible gem. I think one solution is gemsets to ensure the scope of gems available is constrained on a per-project basis. However, I don't really care for rvm (prefer chruby). 

The real question in my mind is: what is causing these gems to be loaded? If we look at my stack trace:
```
/Users/brian.buchalter/.gem/ruby/2.3.4/gems/bundler-1.17.3/lib/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated byebug 11.0.1, but your Gemfile requires byebug 10.0.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/bundler-1.17.3/lib/bundler/runtime.rb:31:in `block in setup'
        from /Users/brian.buchalter/.rubies/ruby-2.3.4/lib/ruby/2.3.0/forwardable.rb:204:in `each'
        from /Users/brian.buchalter/.rubies/ruby-2.3.4/lib/ruby/2.3.0/forwardable.rb:204:in `each'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/bundler-1.17.3/lib/bundler/runtime.rb:26:in `map'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/bundler-1.17.3/lib/bundler/runtime.rb:26:in `setup'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/bundler-1.17.3/lib/bundler/setup.rb:10:in `<top (required)>'
        from /Users/brian.buchalter/.rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /Users/brian.buchalter/.rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /Users/brian.buchalter/.rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /Users/brian.buchalter/workspace/zenpayroll/config/boot.rb:40:in `<top (required)>'
        from /Users/brian.buchalter/.rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/brian.buchalter/.rubies/ruby-2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/zeus-0.15.14/lib/zeus/rails.rb:82:in `boot'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/zeus-0.15.14/lib/zeus.rb:204:in `block in run_action'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:18:in `track_features_loaded_by'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/zeus-0.15.14/lib/zeus.rb:202:in `run_action'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/zeus-0.15.14/lib/zeus.rb:75:in `block in boot_steps'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/zeus-0.15.14/lib/zeus.rb:57:in `catch'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/zeus-0.15.14/lib/zeus.rb:57:in `boot_steps'
        from /Users/brian.buchalter/.gem/ruby/2.3.4/gems/zeus-0.15.14/lib/zeus.rb:49:in `go'
```

My reading of the flow of execution is approximately:
* Setup zeus (from `zeus.rb`)
* Start booting rails (from `zeus/rails.rb`)
* Booting rails invokes `require bundler/setup`
* Bundler starts loading gems
* It seems that a different version $YOUR_PROBLEM_GEMNAME is already activated and raises

Let's look more closely at the code which detects this "already activated" state:
https://github.com/bundler/bundler/blob/master/lib/bundler/runtime.rb#L293-L314

The interesting bit seems to be `activated_spec = Bundler.rubygems.loaded_specs(spec.name)`. So the question is, what else loads specs, before the invocation of `bundler/setup`? I do not know!
