### ISSUE TITLE
Zeus crash makes typing in console invisible

### ISSUE THREAD

**Issue by dalizard** [burke/zeus#404]
I am running zeus 0.13.3 on OSX 10.8.5, iTerm1.0.0.20130624. Every single time zeus crashes, I am no longer able to see what I'm typing in the shell. I recover from the problem by using `reset`. Any suggestions as to what might be causing this? Here's one stacktrace, after which the problem appears:

```
↳ zeus start
Starting Zeus server
exit status 1hed] [running] [connecting] [waiting]
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
    ├── development_environment
    │   └── prerake
    └── test_environment
        └── test_helper

Available Commands: [waiting] [crashed] [ready]
zeus destroy (alias: d)
zeus server (alias: s)
zeus rake
zeus generate (alias: g)
zeus console (alias: c)
zeus runner (alias: r)
zeus dbconsole
zeus test (alias: rspec, testrb)
slavenode.go:202: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x73d27]

goroutine 13 [running]:
github.com/burke/zeus/go/unixsocket.(*Usock).WriteMessage(0x0, 0xf8400f96a0, 0x3a5300000010, 0xf84005d420, 0xe, ...)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/unixsocket/unixsocket.go:81 +0xba
github.com/burke/zeus/go/processtree.(*SlaveNode).bootSlave(0xf8400870d0, 0xf8400871a0, 0x0, 0x5200000001)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:274 +0x10e
github.com/burke/zeus/go/processtree.(*SlaveNode).doCrashedOrReadyState(0xf8400870d0, 0xf800000001, 0x10dadc, 0x4300000001)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:247 +0x142
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xf8400870d0, 0xf84005d800, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:142 +0x184
created by github.com/burke/zeus/go/processtree._func_001
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:52 +0x215

goroutine 1 [select]:
github.com/burke/zeus/go/zeusmaster.doRun(0x0, 0x229c)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/zeusmaster/zeusmaster.go:47 +0x377
github.com/burke/zeus/go/zeusmaster.Run()
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/zeusmaster/zeusmaster.go:22 +0x1c
main.main()
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/cmd/zeus/zeus.go:40 +0x29c

goroutine 2 [syscall]:
created by runtime.main
        /usr/local/Cellar/go/1.0.3/src/pkg/runtime/proc.c:221

goroutine 3 [syscall]:
os/signal.loop()
        /usr/local/Cellar/go/1.0.3/src/pkg/os/signal/signal_unix.go:20 +0x1c
created by os/signal.init·1
        /usr/local/Cellar/go/1.0.3/src/pkg/os/signal/signal_unix.go:26 +0x2f

goroutine 4 [select]:
github.com/burke/zeus/go/filemonitor.start(0xf840097000, 0xf84008a3c0, 0xf84008a410, 0x0, 0x0, ...)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/filemonitor/filemonitor.go:51 +0x148
created by github.com/burke/zeus/go/filemonitor.Start
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/filemonitor/filemonitor.go:21 +0x7e

goroutine 5 [select]:
github.com/burke/zeus/go/processtree._func_001(0xf84005e240, 0xf84005e250, 0xf84005e248, 0x0, 0x0, ...)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:56 +0x314
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:65 +0xb6

goroutine 6 [select]:
github.com/burke/zeus/go/clienthandler._func_001(0xf84005e268, 0xf84005e260, 0xf84005e258, 0x0, 0x0, ...)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/clienthandler/clienthandler.go:47 +0x23c
created by github.com/burke/zeus/go/clienthandler.Start
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/clienthandler/clienthandler.go:56 +0xb6

goroutine 7 [runnable]:
syscall.Syscall()
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/asm_darwin_amd64.s:34 +0x61
syscall.Write(0x1, 0xf840081240, 0x4000000022, 0xf800000000, 0x0, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/zsyscall_darwin_amd64.go:1279 +0x78
os.(*File).write(0xf84005e008, 0xf840081240, 0x4000000022, 0xf800000000, 0x0, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/os/file_unix.go:188 +0x69
os.(*File).Write(0xf84005e008, 0xf840081240, 0x4000000022, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/os/file.go:139 +0x83
fmt.Fprintf(0xf840043a80, 0xf84005e008, 0xf84012cc00, 0xf800000022, 0x0, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/fmt/print.go:214 +0xa4
fmt.Printf(0xf84012cc00, 0x22, 0x0, 0x0, 0x1135f4, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/fmt/print.go:222 +0x97
github.com/burke/zeus/go/statuschart.(*StatusChart).draw(0xf840096c00, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/statuschart/statuschart.go:131 +0x220
github.com/burke/zeus/go/statuschart._func_001(0xf84005e270, 0xf84005e280, 0xf84005e278, 0x0, 0x0, ...)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/statuschart/statuschart.go:76 +0x49f
created by github.com/burke/zeus/go/statuschart.Start
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/statuschart/statuschart.go:83 +0xb6

goroutine 8 [finalizer wait]:
created by runtime.gc
        /usr/local/Cellar/go/1.0.3/src/pkg/runtime/mgc0.c:882

goroutine 9 [syscall]:
created by addtimer
        /usr/local/Cellar/go/1.0.3/src/pkg/runtime/ztime_amd64.c:72

goroutine 10 [syscall]:
syscall.Syscall6()
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/asm_darwin_amd64.s:38 +0x5
syscall.kevent(0x11, 0x0, 0x0, 0xf84006ad88, 0xa, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/zsyscall_darwin_amd64.go:199 +0x88
syscall.Kevent(0xf800000011, 0x0, 0x0, 0xf84006ad88, 0xa0000000a, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/syscall_bsd.go:546 +0xa4
net.(*pollster).WaitFD(0xf84006ad80, 0xf840044d80, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/net/fd_darwin.go:96 +0x185
net.(*pollServer).Run(0xf840044d80, 0x0)
        /usr/local/Cellar/go/1.0.3/src/pkg/net/fd.go:236 +0xe4
created by net.newPollServer
        /usr/local/Cellar/go/1.0.3/src/pkg/net/newpollserver.go:35 +0x382

goroutine 11 [chan receive]:
net.(*pollServer).WaitRead(0xf840044d80, 0xf840064120, 0xf8400ea6c0, 0x23, 0x1, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/net/fd.go:268 +0x73
net.(*netFD).ReadMsg(0xf840064120, 0xf84011d000, 0x40000000400, 0xf840045ba0, 0x2000000020, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/net/fd.go:486 +0x2d5
net.(*UnixConn).ReadMsgUnix(0xf84005e488, 0xf84011d000, 0x40000000400, 0xf840045ba0, 0x2000000020, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/net/unixsock_posix.go:274 +0x144
github.com/burke/zeus/go/unixsocket.(*Usock).readFromSocket(0xf8400ec000, 0x0, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/unixsocket/unixsocket.go:186 +0xf4
github.com/burke/zeus/go/unixsocket.(*Usock).ReadFD(0xf8400ec000, 0xf800000000, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/unixsocket/unixsocket.go:109 +0xaa
github.com/burke/zeus/go/processtree._func_002(0xf84005e318, 0xf84005e490, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:43 +0x28
created by github.com/burke/zeus/go/processtree._func_001
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:49 +0x1a7

goroutine 12 [semacquire]:
sync.runtime_Semacquire(0xf84005e148, 0xf84005e148)
        /usr/local/Cellar/go/1.0.3/src/pkg/runtime/zsema_amd64.c:146 +0x25
sync.(*Cond).Wait(0xf840081440, 0x1)
        /usr/local/Cellar/go/1.0.3/src/pkg/sync/cond.go:67 +0xaa
github.com/burke/zeus/go/processtree.(*SlaveNode).WaitUntilReadyOrCrashed(0xf840087410, 0x51629)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:75 +0x133
github.com/burke/zeus/go/processtree.(*SlaveNode).doWaitingState(0xf8400874e0, 0xf800000001, 0x10e22c, 0x5700000001)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:163 +0x51
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xf8400874e0, 0xf84005d800, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:136 +0x2f2
created by github.com/burke/zeus/go/processtree._func_001
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:52 +0x215

goroutine 14 [semacquire]:
sync.runtime_Semacquire(0xf84005e5d8, 0xf84005e5d8)
        /usr/local/Cellar/go/1.0.3/src/pkg/runtime/zsema_amd64.c:146 +0x25
sync.(*Cond).Wait(0xf840081300, 0x1)
        /usr/local/Cellar/go/1.0.3/src/pkg/sync/cond.go:67 +0xaa
github.com/burke/zeus/go/processtree.(*SlaveNode).WaitUntilReadyOrCrashed(0xf8400871a0, 0x51629)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:75 +0x133
github.com/burke/zeus/go/processtree.(*SlaveNode).doWaitingState(0xf840087270, 0xf800000001, 0x10e22c, 0x5700000001)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:163 +0x51
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xf840087270, 0xf84005d800, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:136 +0x2f2
created by github.com/burke/zeus/go/processtree._func_001
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:52 +0x215

goroutine 15 [semacquire]:
sync.runtime_Semacquire(0xf84005e4a8, 0xf84005e4a8)
        /usr/local/Cellar/go/1.0.3/src/pkg/runtime/zsema_amd64.c:146 +0x25
sync.(*Cond).Wait(0xf840081340, 0x1)
        /usr/local/Cellar/go/1.0.3/src/pkg/sync/cond.go:67 +0xaa
github.com/burke/zeus/go/processtree.(*SlaveNode).WaitUntilReadyOrCrashed(0xf840087270, 0x51629)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:75 +0x133
github.com/burke/zeus/go/processtree.(*SlaveNode).doWaitingState(0xf840087340, 0xf800000001, 0x10e22c, 0x5700000001)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:163 +0x51
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xf840087340, 0xf84005d800, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:136 +0x2f2
created by github.com/burke/zeus/go/processtree._func_001
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:52 +0x215

goroutine 16 [semacquire]:
sync.runtime_Semacquire(0xf84005e5d8, 0x1915f)
        /usr/local/Cellar/go/1.0.3/src/pkg/runtime/zsema_amd64.c:146 +0x25
sync.(*Cond).Wait(0xf840081300, 0x1)
        /usr/local/Cellar/go/1.0.3/src/pkg/sync/cond.go:67 +0xaa
github.com/burke/zeus/go/processtree.(*SlaveNode).WaitUntilReadyOrCrashed(0xf8400871a0, 0x51629)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:75 +0x133
github.com/burke/zeus/go/processtree.(*SlaveNode).doWaitingState(0xf840087410, 0xf800000001, 0x10e22c, 0x5700000001)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:163 +0x51
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xf840087410, 0xf84005d800, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:136 +0x2f2
created by github.com/burke/zeus/go/processtree._func_001
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:52 +0x215

goroutine 17 [chan receive]:
github.com/burke/zeus/go/processtree.(*SlaveNode).doUnbootedState(0xf8400871a0, 0xf84005d800, 0x0, 0x5500000000, 0x0, ...)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:184 +0x3d4
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xf8400871a0, 0xf84005d800, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavenode.go:138 +0x294
created by github.com/burke/zeus/go/processtree._func_001
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:52 +0x215

goroutine 19 [syscall]:
syscall.Syscall()
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/asm_darwin_amd64.s:14 +0x5
syscall.Read(0x230000000b, 0xf840103000, 0x80000000800, 0x100000001, 0x0, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/zsyscall_darwin_amd64.go:905 +0x78
os.(*File).read(0xf84005e3e0, 0xf840103000, 0x80000000800, 0x80000000800, 0x0, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/os/file_unix.go:174 +0x58
os.(*File).Read(0xf84005e3e0, 0xf840103000, 0x80000000800, 0xf840103000, 0x0, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/os/file.go:95 +0x83
github.com/burke/zeus/go/filemonitor._func_001(0xf84005e288, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/filemonitor/filemonitor.go:92 +0x87
created by github.com/burke/zeus/go/filemonitor.startWrapper
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/filemonitor/filemonitor.go:103 +0x22f

goroutine 20 [syscall]:
syscall.Syscall6()
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/asm_darwin_amd64.s:38 +0x5
syscall.wait4(0x7925, 0xf84005e4e8, 0x0, 0xf840064240, 0x1, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/zsyscall_darwin_amd64.go:32 +0x81
syscall.Wait4(0x7925, 0x226de34, 0x0, 0xf840064240, 0x0, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/syscall/syscall_bsd.go:136 +0x6a
os.(*Process).wait(0xf840045d60, 0x0, 0x0, 0x0, 0x9e551, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/os/exec_unix.go:22 +0xe1
os.(*Process).Wait(0xf840045d60, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.0.3/src/pkg/os/doc.go:43 +0x25
os/exec.(*Cmd).Wait(0xf840069000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.0.3/src/pkg/os/exec/exec.go:308 +0x1b7
github.com/burke/zeus/go/filemonitor._func_002(0xf84005e290, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/filemonitor/filemonitor.go:106 +0x29
created by github.com/burke/zeus/go/filemonitor.startWrapper
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/filemonitor/filemonitor.go:111 +0x246

goroutine 22 [chan receive]:
net.(*pollServer).WaitRead(0xf840044d80, 0xf84011a000, 0xf8400ea6c0, 0x23, 0x1, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/net/fd.go:268 +0x73
net.(*netFD).accept(0xf84011a000, 0x641a5, 0x0, 0xf840043480, 0xf84005e040, ...)
        /usr/local/Cellar/go/1.0.3/src/pkg/net/fd.go:622 +0x20d
net.(*UnixListener).AcceptUnix(0xf8400455c0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.0.3/src/pkg/net/unixsock_posix.go:350 +0x4d
github.com/burke/zeus/go/clienthandler._func_002(0xf84005e3f8, 0xf84005e038, 0x0, 0x0)
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/clienthandler/clienthandler.go:37 +0x28
created by github.com/burke/zeus/go/clienthandler._func_001
        /Users/turadg/Code/Go/src/github.com/burke/zeus/go/clienthandler/clienthandler.go:44 +0x15a
Bilbo:dimitar user_service (master)
```

**Comment by dalizard** [comment]
The issue is very old now, probably not relevant.
