### ISSUE TITLE
spec_helper.rb:17:in `<top (required)>': undefined method `configure' for RSpec:Module (NoMethodError)

### ISSUE THREAD

**Issue by PaBLoX-CL** [burke/zeus#474]
I'm running a new rails 4.1 app with rspec 3.0, and zeus 0.15.1.

```
❯❯❯ zeus test
/home/pablo/code/rails/pescve/spec/spec_helper.rb:17:in `<top (required)>': undefined method `configure' for RSpec:Module (NoMethodError)
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `block in require'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
	from /home/pablo/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus/rails.rb:189:in `test_helper'
	from /home/pablo/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus.rb:200:in `run_action'
	from /home/pablo/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus.rb:74:in `block (2 levels) in boot_steps'
	from /home/pablo/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus/load_tracking.rb:7:in `features_loaded_by'
	from /home/pablo/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus.rb:73:in `block in boot_steps'
	from /home/pablo/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus.rb:56:in `catch'
	from /home/pablo/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus.rb:56:in `boot_steps'
	from /home/pablo/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus.rb:48:in `go'
	from -e:1:in `<main>'
```

If I add `require rspec/rails` on the top, zeus works, but rspec stops working:

```
❯❯❯ rspec spec
/home/pablo/code/rails/pescve/vendor/bundle/gems/actionview-4.1.2/lib/action_view/template.rb:8:in `<class:Template>': uninitialized constant ActiveSupport::Autoload (NameError)
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/actionview-4.1.2/lib/action_view/template.rb:7:in `<module:ActionView>'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/actionview-4.1.2/lib/action_view/template.rb:5:in `<top (required)>'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/actionview-4.1.2/lib/action_view/template/resolver.rb:4:in `require'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/actionview-4.1.2/lib/action_view/template/resolver.rb:4:in `<top (required)>'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/actionview-4.1.2/lib/action_view/testing/resolvers.rb:1:in `require'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/actionview-4.1.2/lib/action_view/testing/resolvers.rb:1:in `<top (required)>'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-rails-3.0.1/lib/rspec/rails/view_rendering.rb:1:in `require'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-rails-3.0.1/lib/rspec/rails/view_rendering.rb:1:in `<top (required)>'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-rails-3.0.1/lib/rspec/rails.rb:4:in `require'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-rails-3.0.1/lib/rspec/rails.rb:4:in `<top (required)>'
	from /home/pablo/code/rails/pescve/spec/spec_helper.rb:18:in `require'
	from /home/pablo/code/rails/pescve/spec/spec_helper.rb:18:in `<top (required)>'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1024:in `require'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1024:in `block in requires='
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1024:in `each'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/configuration.rb:1024:in `requires='
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/configuration_options.rb:101:in `block in process_options_into'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/configuration_options.rb:100:in `each'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/configuration_options.rb:100:in `process_options_into'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:96:in `setup'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:85:in `run'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:70:in `run'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/lib/rspec/core/runner.rb:38:in `invoke'
	from /home/pablo/code/rails/pescve/vendor/bundle/gems/rspec-core-3.0.2/exe/rspec:4:in `<top (required)>'
	from /home/pablo/code/rails/pescve/bin/rspec:16:in `load'
	from /home/pablo/code/rails/pescve/bin/rspec:16:in `<main>'
```

I'm pretty sure this error appeared after having `spec/rails_helper.rb` and `spec/spec_helper.rb`, but I don't know how to fix it =/. Any idea?

```ruby
# spec/rails_helper.rb

# This file is copied to spec/ when you run 'rails generate rspec:install'
ENV["RAILS_ENV"] ||= 'test'
require 'spec_helper'
require File.expand_path("../../config/environment", __FILE__)
require 'fabrication'
require 'rspec/rails'

# Requires supporting ruby files with custom matchers and macros, etc, in
# spec/support/ and its subdirectories. Files matching `spec/**/*_spec.rb` are
# run as spec files by default. This means that files in spec/support that end
# in _spec.rb will both be required and run as specs, causing the specs to be
# run twice. It is recommended that you do not name files matching this glob to
# end with _spec.rb. You can configure this pattern with with the --pattern
# option on the command line or in ~/.rspec, .rspec or `.rspec-local`.
Dir[Rails.root.join("spec/support/**/*.rb")].each { |f| require f }

# Checks for pending migrations before tests are run.
# If you are not using ActiveRecord, you can remove this line.
# ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|
  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  # config.fixture_path = "#{::Rails.root}/spec/fixtures"

  # If you're not using ActiveRecord, or you'd prefer not to run each of your
  # examples within a transaction, remove the following line or assign false
  # instead of true.
  # config.use_transactional_fixtures = true

  # RSpec Rails can automatically mix in different behaviours to your tests
  # based on their file location, for example enabling you to call `get` and
  # `post` in specs under `spec/controllers`.
  #
  # You can disable this behaviour by removing the line below, and instead
  # explicitly tag your specs with their type, e.g.:
  #
  #     RSpec.describe UsersController, :type => :controller do
  #       # ...
  #     end
  #
  # The different available types are documented in the features, such as in
  # https://relishapp.com/rspec/rspec-rails/docs
  config.infer_spec_type_from_file_location!
end
```
```ruby
# spec/spec_helper

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause this
# file to always be loaded, without a need to explicitly require it in any files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, make a
# separate helper file that requires this one and then use it only in the specs
# that actually need it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

RSpec.configure do |config|
# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # These two settings work together to allow you to limit a spec run
  # to individual examples or groups you care about by tagging them with
  # `:focus` metadata. When nothing is tagged with `:focus`, all examples
  # get run.
  config.filter_run :focus
  config.run_all_when_everything_filtered = true

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = 'doc'
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed

  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # Enable only the newer, non-monkey-patching expect syntax.
    # For more details, see:
    #   - http://myronmars.to/n/dev-blog/2012/06/rspecs-new-expectation-syntax
    expectations.syntax = :expect
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Enable only the newer, non-monkey-patching expect syntax.
    # For more details, see:
    #   - http://teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
    mocks.syntax = :expect

    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended.
    mocks.verify_partial_doubles = true
  end
=end
end
```

**Comment by latortuga** [comment]
Thanks for the report @johvet

**Comment by ineu** [comment]
Shouldn't it be fixed on rspec side by requiring 'rspec/core' at the beginning of spec_helper.rb?

**Comment by lazywei** [comment]
Just confirmed that I still have this issue in Rails 4.2.0.rc1 / Rspec 3.2.0 / Zeus 0.15.4 . @maxcal 's trick fixes the issue.

**Comment by xiy** [comment]
Easily solved, in your Gemfile:

`require "rspec-rails", require: "rspec/rails"`

:dancer:

**Comment by rickypai** [comment]
:dancer: :dancer: :dancer:

**Comment by halilim** [comment]
@hayeah, your fix gives the error:

    .../rack-1.6.4/lib/rack/builder.rb:146:in `to_app': missing run or map statement (RuntimeError)

**Comment by hayeah** [comment]
@halilim no idea. I followed https://github.com/burke/zeus/issues/474#issuecomment-89336625 and it worked in our case.

**Comment by eladg** [comment]
@halilim, experienced the same error here... although I'm not using Zeus (just got here though google).

**Comment by przbadu** [comment]
Yep adding `require 'rspec/core'` before requiring `spec_helper` in `rails_helper.rb` solved the problem.

`rails_helper.rb`
```ruby
require 'rspec/core'
require 'spec_helper'
```

**Comment by Gaolz** [comment]
I met the same problem, Also adding `require 'rspec/rails` before requring `spec_helper` in `rails_helper.rb` solved the problem.

```
# rails_helper.rb

require "rspec/rails"
require "spec_helper"
```

**Comment by ajsharp** [comment]
I agree with some of the previous comments here. Currently, zeus doesn't work with a stock rails 4+/5 setup and rspec setup -- `rails_helper.rb` must be modified for zeus to function at all. Being that this is the case, either:

a. zeus should be changed to support the default rails behavior
b. The zeus documentation should clearly lay out these required changes to `rails_helper.rb`.
