### ISSUE TITLE
Panic on CTRL+C while zeus start is loading

### ISSUE THREAD

**Issue by thedrow** [burke/zeus#587]
```
panic: send on closed channel

goroutine 52 [running]:
panic(0x416aae0, 0xc82000ef30)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/burke/zeus/go/filemonitor.(*fsEventsMonitor).Add(0xc820010fc0, 0xc82029a150, 0x65, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/filemonitor/filemonitor_darwin.go:40 +0x5b
github.com/burke/zeus/go/processtree.(*SlaveNode).handleMessages(0xc8200ba380, 0xc8200e0088)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:414 +0x251
created by github.com/burke/zeus/go/processtree.(*SlaveNode).SlaveWasInitialized
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:124 +0x38d
panic: send on closed channel

goroutine 37 [running]:
panic(0x416aae0, 0xc8200e62d0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/burke/zeus/go/filemonitor.(*fsEventsMonitor).Add(0xc820010fc0, 0xc8200fc7e0, 0x6a, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/filemonitor/filemonitor_darwin.go:40 +0x5b
github.com/burke/zeus/go/processtree.(*SlaveNode).handleMessages(0xc8200ba1c0, 0xc820124018)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:414 +0x251
created by github.com/burke/zeus/go/processtree.(*SlaveNode).SlaveWasInitialized
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:124 +0x38d
```

**Comment by sideshowcoder** [comment]
I'm not really sure what to make of this @thedrow any chance you could elaborate?

**Comment by thedrow** [comment]
Yes I started Zeus and then typed Ctrl+C in order to stop it.

**Comment by sideshowcoder** [comment]
Mh.. @thedrow is this reproducible for you? I tried on both mac an linux but can't see it happening, what would potentially help is:

- what version of zeus are you using
- what os are you using and what version (I assume Mac due to directory structure, but not sure which version)
- anything else that might help?

Thanks for your help!

**Comment by thedrow** [comment]
I no longer have access to that machine but I did see it happening from time to time. 
I was using the latest Zeus version and OS X Sierra.
