### ISSUE TITLE
Zeus consistently crashing on Sierra

### ISSUE THREAD

**Issue by Ommy** [burke/zeus#610]
Everytime I run `zeus` now, it crashes after a couple of seconds. 

```
$ uname -a
Darwin fasih.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ go version
go version go1.7 darwin/amd64
```

Here's the log:

```
$ zeus --log /dev/stderr start
Starting Zeus server v0.15.10
2016/11/15 20:53:42.181500 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] prerake/(no PID) entering state SUnbooted
2016/11/15 20:53:42.181524 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] default_bundle/(no PID) entering state SUnbooted
2016/11/15 20:53:42.181544 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] boot/(no PID) entering state SUnbooted
2016/11/15 20:53:42.181557 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] development_environment/(no PID) entering state SUnbooted
2016/11/15 20:53:42.181588 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] test_helper/(no PID) entering state SUnbooted
2016/11/15 20:53:42.181689 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] test_environment/(no PID) entering state SUnbooted
2016/11/15 20:53:42.181799 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:373] boot/(no PID) running the root command now
[ready] [crashed] [running] [connecting] [waiting]
boot
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
[ready] [crashed] [running] [connecting] [waiting]
boot
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
    ├── development_environment
    │   └── prerake
    └── test_environment
        └── test_helper

Available Commands: [waiting] [crashed] [ready]
zeus generate (alias: g)
zeus destroy (alias: d)
zeus dbconsole
zeus rake
zeus runner (alias: r)
zeus console (alias: c)
zeus server (alias: s)
zeus test (alias: rspec, testrb)
2016/11/15 20:53:49.239965 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:211] default_bundle/(13371) received action message
2016/11/15 20:53:49.240001 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:148] default_bundle/(no PID) entering state SCrashed
2016/11/15 20:53:49.240017 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:142] test_environment/(no PID) entering state SBooting
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x413a0d9]

goroutine 24 [running]:
panic(0x41ad260, 0xc820010270)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/burke/zeus/go/unixsocket.(*Usock).ReadMessage(0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/unixsocket/usock.go:52 +0x169
github.com/burke/zeus/go/processtree.(*SlaveNode).doBootingState(0xc8200cc380, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:207 +0x46
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xc8200cc380, 0xc8200be260)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:143 +0x1c5
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:53 +0x27f
```

**Comment by Ommy** [comment]
I ran the update of Sierra to 10.12.1 and running again I get the following:
```
Starting Zeus server v0.15.10
2016/11/15 21:01:57.306950 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] test_helper/(no PID) entering state SUnbooted
2016/11/15 21:01:57.306975 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] prerake/(no PID) entering state SUnbooted
2016/11/15 21:01:57.306993 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] test_environment/(no PID) entering state SUnbooted
2016/11/15 21:01:57.307048 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] development_environment/(no PID) entering state SUnbooted
2016/11/15 21:01:57.307052 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] boot/(no PID) entering state SUnbooted
2016/11/15 21:01:57.307201 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:373] boot/(no PID) running the root command now
2016/11/15 21:01:57.307064 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:139] default_bundle/(no PID) entering state SUnbooted
[ready] [crashed] [running] [connecting] [waiting]
boot
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
    ├── development_environment
    │   └── prerake
    └── test_environment
        └── test_helper

Available Commands: [waiting] [crashed] [ready]
zeus rake
zeus runner (alias: r)
zeus console (alias: c)
zeus server (alias: s)
zeus generate (alias: g)
zeus destroy (alias: d)
zeus dbconsole
zeus test (alias: rspec, testrb)
1969/12/31 16:00:00.000000 [/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:211] boot/(3341) received action message
slavenode.go:209: read unix ->: EOF
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x22b949a4d4 pc=0x40d64f0]

goroutine 19 [running]:
runtime.throw(0x4227b00, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc82012ac78 sp=0xc82012ac60
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82012acc8 sp=0xc82012ac78
sync.(*Pool).Get(0x42e5390, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/pool.go:102 +0x40 fp=0xc82012ad18 sp=0xc82012acc8
fmt.newPrinter(0x10)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:133 +0x27 fp=0xc82012ad58 sp=0xc82012ad18
fmt.Sprintf(0x420aac0, 0x13, 0xc82012aea0, 0x3, 0x3, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:202 +0x2b fp=0xc82012ada8 sp=0xc82012ad58
github.com/burke/zeus/go/processtree.(*SlaveNode).trace(0xc8200aa000, 0x420cc60, 0x17, 0x0, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:430 +0x800 fp=0xc82012af18 sp=0xc82012ada8
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xc8200aa000, 0xc820108000)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:148 +0x26f fp=0xc82012afa0 sp=0xc82012af18
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82012afa8 sp=0xc82012afa0
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:53 +0x27f

goroutine 1 [chan receive]:
github.com/burke/zeus/go/zeusmaster.Run(0x41f2e90, 0x9, 0x11e1a300, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/zeusmaster/zeusmaster.go:54 +0x35a
main.main()
	/Users/andrew/code/go/src/github.com/burke/zeus/go/cmd/zeus/zeus.go:78 +0x5e5

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/burke/zeus/go/filemonitor.(*fsEventsMonitor).handleAdd(0xc82000a800)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/filemonitor/filemonitor_darwin.go:86 +0x110
created by github.com/burke/zeus/go/filemonitor.NewFileMonitor
	/Users/andrew/code/go/src/github.com/burke/zeus/go/filemonitor/filemonitor_darwin.go:34 +0x1e8

goroutine 7 [select]:
github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1(0xc82000a880, 0xc820018d20, 0xc820018c60, 0xc820018cc0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:57 +0x455
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:67 +0x71

goroutine 8 [select]:
github.com/burke/zeus/go/clienthandler.Start.func1(0xc820018d80, 0xc820018c60, 0xc82000a880)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/clienthandler/clienthandler.go:45 +0x286
created by github.com/burke/zeus/go/clienthandler.Start
	/Users/andrew/code/go/src/github.com/burke/zeus/go/clienthandler/clienthandler.go:54 +0x67

goroutine 9 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/burke/zeus/go/statuschart.ttyStart
	/Users/andrew/code/go/src/github.com/burke/zeus/go/statuschart/tty.go:50 +0x3f

goroutine 10 [select]:
github.com/burke/zeus/go/statuschart.(*StatusChart).watchUpdates(0xc8200b2080, 0xc82005a150)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/statuschart/statuschart.go:62 +0x14a
created by github.com/burke/zeus/go/statuschart.Start
	/Users/andrew/code/go/src/github.com/burke/zeus/go/statuschart/statuschart.go:51 +0x43b

goroutine 11 [select, locked to thread]:
runtime.gopark(0x423aab0, 0xc820026f28, 0x41ea5b8, 0x6, 0x18, 0x2)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820026f28, 0x0, 0x18)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820026f28)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/signal1_unix.go:279 +0x32c
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 18 [IO wait]:
net.runtime_pollWait(0x5140f30, 0x72, 0xc8200f5ac4)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820112060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820112060, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readMsg(0xc820112000, 0xc8200f5e88, 0x0, 0x0, 0xc820106080, 0x20, 0x20, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:304 +0x33d
net.(*UnixConn).ReadMsgUnix(0xc8200f8010, 0xc8200f5e88, 0x0, 0x0, 0xc820106080, 0x20, 0x20, 0x1, 0x10, 0x0, ...)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/unixsock_posix.go:150 +0x15f
github.com/burke/zeus/go/unixsocket.(*oobReader).Read(0xc82010a0c0, 0xc8200f5e88, 0x0, 0x0, 0x40091a3, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/unixsocket/oobreader.go:39 +0x8b
github.com/burke/zeus/go/unixsocket.(*oobReader).ReadFD(0xc82010a0c0, 0x423ab50, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/unixsocket/oobreader.go:24 +0x188
github.com/burke/zeus/go/unixsocket.(*Usock).ReadFD(0xc8201060a0, 0x0, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/unixsocket/usock.go:79 +0x90
github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1.1(0xc8201060a0, 0xc820110100)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:44 +0x21
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:50 +0x1ea

goroutine 20 [chan receive]:
github.com/burke/zeus/go/processtree.(*SlaveNode).doUnbootedState(0xc8200aa0e0, 0xc820108000, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:190 +0x444
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xc8200aa0e0, 0xc820108000)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:140 +0x42b
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:53 +0x27f

goroutine 21 [chan receive]:
github.com/burke/zeus/go/processtree.(*SlaveNode).doUnbootedState(0xc8200aa1c0, 0xc820108000, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:190 +0x444
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xc8200aa1c0, 0xc820108000)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:140 +0x42b
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:53 +0x27f

goroutine 22 [chan receive]:
github.com/burke/zeus/go/processtree.(*SlaveNode).doUnbootedState(0xc8200aa2a0, 0xc820108000, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:190 +0x444
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xc8200aa2a0, 0xc820108000)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:140 +0x42b
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:53 +0x27f

goroutine 23 [chan receive]:
github.com/burke/zeus/go/processtree.(*SlaveNode).doUnbootedState(0xc8200aa380, 0xc820108000, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:190 +0x444
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xc8200aa380, 0xc820108000)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:140 +0x42b
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:53 +0x27f

goroutine 24 [chan receive]:
github.com/burke/zeus/go/processtree.(*SlaveNode).doUnbootedState(0xc8200aa460, 0xc820108000, 0x0, 0x0)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:190 +0x444
github.com/burke/zeus/go/processtree.(*SlaveNode).Run(0xc8200aa460, 0xc820108000)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:140 +0x42b
created by github.com/burke/zeus/go/processtree.StartSlaveMonitor.func1
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavemonitor.go:53 +0x27f

goroutine 34 [IO wait]:
net.runtime_pollWait(0x5140e70, 0x72, 0x4650050)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82010c060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82010c060, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82010c000, 0x0, 0x5100070, 0xc820102060)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/fd_unix.go:426 +0x27c
net.(*UnixListener).AcceptUnix(0xc820102040, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/unixsock_posix.go:305 +0x53
github.com/burke/zeus/go/clienthandler.Start.func1.1(0xc820102040, 0xc820124000)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/clienthandler/clienthandler.go:35 +0x33
created by github.com/burke/zeus/go/clienthandler.Start.func1
	/Users/andrew/code/go/src/github.com/burke/zeus/go/clienthandler/clienthandler.go:42 +0x160

goroutine 25 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/burke/zeus/go/processtree.(*SlaveNode).doUnbootedState
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:184 +0x3f3
[signal 0xb code=0x1 addr=0x22b949a374 pc=0x40d64f0]

goroutine 25 [running]:
runtime.throw(0x4227b00, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc8200f1b58 sp=0xc8200f1b40
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8200f1ba8 sp=0xc8200f1b58
sync.(*Pool).Get(0x42e5390, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/pool.go:102 +0x40 fp=0xc8200f1bf8 sp=0xc8200f1ba8
fmt.newPrinter(0x10)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:133 +0x27 fp=0xc8200f1c38 sp=0xc8200f1bf8
fmt.Sprintf(0x420aac0, 0x13, 0xc8200f1d80, 0x3, 0x3, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:202 +0x2b fp=0xc8200f1c88 sp=0xc8200f1c38
github.com/burke/zeus/go/processtree.(*SlaveNode).trace(0xc8200aa000, 0x422e300, 0x4a, 0xc8200f1f48, 0x2, 0x2)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:430 +0x800 fp=0xc8200f1df8 sp=0xc8200f1c88
github.com/burke/zeus/go/processtree.(*SlaveNode).babysitRootProcess(0xc8200aa000, 0xc82016c140)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:384 +0x42c fp=0xc8200f1fa0 sp=0xc8200f1df8
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200f1fa8 sp=0xc8200f1fa0
created by github.com/burke/zeus/go/processtree.(*SlaveNode).doUnbootedState
	/Users/andrew/code/go/src/github.com/burke/zeus/go/processtree/slavenode.go:184 +0x3f3
[signal 0xb code=0x1 addr=0x22b949a424 pc=0x40d64f0]

goroutine 9 [running]:
runtime.throw(0x4227b00, 0x2a)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x90 fp=0xc8200f4a98 sp=0xc8200f4a80
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8200f4ae8 sp=0xc8200f4a98
sync.(*Pool).Get(0x42e5390, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/pool.go:102 +0x40 fp=0xc8200f4b38 sp=0xc8200f4ae8
fmt.newPrinter(0xc820170360)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:133 +0x27 fp=0xc8200f4b78 sp=0xc8200f4b38
fmt.Fprintf(0x4654308, 0xc82002e010, 0x41e9020, 0x5, 0xc8200f4ca0, 0x1, 0x1, 0x401169e, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:187 +0x30 fp=0xc8200f4bc0 sp=0xc8200f4b78
fmt.Printf(0x41e9020, 0x5, 0xc8200f4ca0, 0x1, 0x1, 0x2d, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/fmt/print.go:197 +0x94 fp=0xc8200f4c28 sp=0xc8200f4bc0
github.com/burke/zeus/go/statuschart.(*StatusChart).draw(0xc8200b2080)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/statuschart/tty.go:60 +0x19b fp=0xc8200f4cd0 sp=0xc8200f4c28
github.com/burke/zeus/go/statuschart.ttyStart.func1(0xc820018de0, 0xc820018c60)
	/Users/andrew/code/go/src/github.com/burke/zeus/go/statuschart/tty.go:45 +0x58f fp=0xc8200f4fa0 sp=0xc8200f4cd0
runtime.goexit()
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200f4fa8 sp=0xc8200f4fa0
created by github.com/burke/zeus/go/statuschart.ttyStart
	/Users/andrew/code/go/src/github.com/burke/zeus/go/statuschart/tty.go:50 +0x3f
```

**Comment by Ommy** [comment]
I was able to resolve this issue by running a `gem pristine --all`.
