### ISSUE TITLE
Zeus and FactoryGirl Issue

### ISSUE THREAD

**Issue by jeremiahlukus** [burke/zeus#635]
Once I implemented FactoryGirl my zeus server crashed. 

boot (pass)
└── default_bundle (pass)
    ├── development_environment (crashed)
    │   └── prerake (crashed)
    └── test_environment  (crashed)
        └── test_helper  (crashed)

Here is the trace back running a rspec tests

``` 
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/syntax/default.rb:18:in `factory'
	from /Users/jeremiahlukus/railsApps/timeLog/spec/factories/users.rb:2:in `block in <top (required)>'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/syntax/default.rb:49:in `run'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/syntax/default.rb:7:in `define'
	from /Users/jeremiahlukus/railsApps/timeLog/spec/factories/users.rb:1:in `<top (required)>'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/zeus-0.15.13/lib/zeus/load_tracking.rb:82:in `load'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/zeus-0.15.13/lib/zeus/load_tracking.rb:82:in `load'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/zeus-0.15.13/lib/zeus/load_tracking.rb:74:in `load'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/find_definitions.rb:19:in `each'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/find_definitions.rb:15:in `each'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.8.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/factory_girl_rails-4.8.0/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/lazy_load_hooks.rb:41:in `execute_hook'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/lazy_load_hooks.rb:49:in `each'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/railties-5.0.2/lib/rails/application/finisher.rb:65:in `block in <module:Finisher>'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/jeremiahlukus/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/jeremiahlukus/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/jeremiahlukus/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/jeremiahlukus/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/jeremiahlukus/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/jeremiahlukus/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/jeremiahlukus/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/jeremiahlukus/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/jeremiahlukus/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
	from /Users/jeremiahlukus/railsApps/timeLog/config/environment.rb:5:in `<top (required)>'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/zeus-0.15.13/lib/zeus/rails.rb:177:in `test_environment'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/zeus-0.15.13/lib/zeus.rb:203:in `block in run_action'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/zeus-0.15.13/lib/zeus/load_tracking.rb:18:in `track_features_loaded_by'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/zeus-0.15.13/lib/zeus.rb:201:in `run_action'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/zeus-0.15.13/lib/zeus.rb:74:in `block in boot_steps'
	from /Users/jeremiahlukus/.rvm/gems/ruby-2.3.0/gems/zeus-0.15.13/lib/zeus.rb:56:in `catch`
```

**Comment by jeremiahlukus** [comment]
re-installed works now
